# Site
repository: my-modern-resume
favicon: images/favicon.ico

# Personal info
name: Pierre-Olivier Renard
title: Ingénieur Industriel
email: pierreolivier.renard.job@gmail.com
website: renard.website

# Social links
# twitter_username: ///
# github_username:  ///
# dribbble_username: jekyll
# facebook_username: pierreolivier.renard.3
# flickr_username: jekyll
# instagram_username: ///
linkedin_username: Pierre-Olivier Renard
# pinterest_username: jekyll
# youtube_username: ///
# googleplus_username: +jekyll

# About Section
about_title: Profil
about_profile_image: images/photoprofil.png
about_content: | # this will include new lines to allow paragraphs
  Ingénieur de formation, j’ai toujours aimé les sciences et leurs applications concrètes en entreprise. J'ai pu mettre à l'épreuve mes connaissances d'organisation SCRUM en accompagnant les membres de l'équipe sur les projets. La compréhension du besoin client, l'étude de la solution technique, son intégration et sa mise en place en atelier m’ont permis d’avoir une vue « End to End » des projets.

  #I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
